---

- hosts: dev
  connection: ssh

  tasks:
    - name: create multiple groups
      group:
        name: "{{ item }}"
        state: present
      with_items:
        - sai
        - resu
        - killer
        - kasi
        - ruler 
